version: '3.8'
services:
  postgres-service:
    image: postgres:alpine
    restart: always
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes: 
     - ./postgres_data:/var/lib/postgresql/data
